language: java
jdk: openjdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean
  - mvn -pl application test

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
